version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo Preparing build with Python 3.7 runtime...
  pre_build:
    commands:
      - echo logging in to AWS ECR...
      - $(aws ecr get-login --no-include-email --region ap-northeast-1)
  build:
    commands:
      - echo build Docker image on `date`
      - docker build -t test-python:latest .
      - docker tag test-python:latest 224982748301.dkr.ecr.ap-northeast-1.amazonaws.com/test-python
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest Docker images to ECR...
      - docker push 224982748301.dkr.ecr.ap-northeast-1.amazonaws.com/test-python
